[workspace]
members = [
    "curve",
    "curve25519",
    "r1cs",
    "groth16",
    "bulletproofs",
    "marlin",
    "plonk",
    "clinkv2",
    "asvc",
    "spartan",
    "libra",
    "hyrax",
    "gadgets",
    "examples",
    "cli",
]
exclude = [
    "ckb-contracts/bench-tests",
]
