[package]
name = "zkp-examples"
version = "0.1.0"
authors = ["SECBIT Labs"]
description = "zkp examples."
keywords = ["cryptography", "zkp", "zero-knowledge"]
categories = ["cryptography"]
license = "MIT/Apache-2.0"
edition = "2018"