[package]
name = "universal_marlin_verifier"
version = "0.1.0"
edition = "2018"

[dependencies]
ckb-std = "0.7.3"

[dependencies.zkp-marlin]
git = "https://github.com/sec-bit/ckb-zkp"
branch = "dev"
default-features = false

[dependencies.ark-bls12-381]
git = "https://github.com/arkworks-rs/curves"
default-features = false
features = ["curve"]

[dependencies.ark-serialize]
git = "https://github.com/arkworks-rs/algebra"
default-features = false